[project]
name = "Weather Tool Chatbot"
description = "A chatbot that provides weather information."

[settings]
enable_telemetry = true
session_timeout = 3600

[features]
unsafe_allow_html = false
latex = false
auto_tag_thread = true
edit_message = true

[UI]
name = "Weather Assistant"
default_collapse_content = true
